# Generated by Django 6.0.4 on 2026-04-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Need',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('food', 'Food'), ('medical', 'Medical'), ('shelter', 'Shelter'), ('education', 'Education'), ('other', 'Other')], max_length=50)),
                ('urgency_score', models.FloatField(default=0.0)),
                ('location_lat', models.FloatField(default=0.0)),
                ('location_lng', models.FloatField(default=0.0)),
                ('area_name', models.CharField(default='', max_length=200)),
                ('status', models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('source_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
